/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RoueRouteImport } from './routes/roue'
import { Route as MSlugIndexRouteImport } from './routes/m.$slug.index'
import { Route as MSlugRoueRouteImport } from './routes/m.$slug.roue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RoueRoute = RoueRouteImport.update({
  id: '/roue',
  path: '/roue',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugIndexRoute = MSlugIndexRouteImport.update({
  id: '/m/$slug/',
  path: '/m/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoueRoute = MSlugRoueRouteImport.update({
  id: '/roue',
  path: '/roue',
  getParentRoute: () => MSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/roue': typeof RoueRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug/': typeof MSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/roue': typeof RoueRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug': typeof MSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/roue': typeof RoueRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug/': typeof MSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/onboarding'
    | '/roue'
    | '/m/$slug/roue'
    | '/m/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/onboarding'
    | '/roue'
    | '/m/$slug/roue'
    | '/m/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/onboarding'
    | '/roue'
    | '/m/$slug/roue'
    | '/m/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  InscriptionRoute: typeof InscriptionRoute
  OnboardingRoute: typeof OnboardingRoute
  RoueRoute: typeof RoueRoute
  MSlugIndexRoute: typeof MSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roue': {
      id: '/roue'
      path: '/roue'
      fullPath: '/roue'
      preLoaderRoute: typeof RoueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug/': {
      id: '/m/$slug/'
      path: '/m/$slug'
      fullPath: '/m/$slug/'
      preLoaderRoute: typeof MSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug/roue': {
      id: '/m/$slug/roue'
      path: '/roue'
      fullPath: '/m/$slug/roue'
      preLoaderRoute: typeof MSlugRoueRouteImport
      parentRoute: typeof MSlugRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmationRoute: ConfirmationRoute,
  InscriptionRoute: InscriptionRoute,
  OnboardingRoute: OnboardingRoute,
  RoueRoute: RoueRoute,
  MSlugIndexRoute: MSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
