/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesSuspenduRouteImport } from './routes/acces-suspendu'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoueRouteImport } from './routes/roue'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as MSlugIndexRouteImport } from './routes/m.$slug.index'
import { Route as MSlugRoueRouteImport } from './routes/m.$slug.roue'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesSuspenduRoute = AccesSuspenduRouteImport.update({
  id: '/acces-suspendu',
  path: '/acces-suspendu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoueRoute = RoueRouteImport.update({
  id: '/roue',
  path: '/roue',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugIndexRoute = MSlugIndexRouteImport.update({
  id: '/m/$slug/',
  path: '/m/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoueRoute = MSlugRoueRouteImport.update({
  id: '/m/$slug/roue',
  path: '/m/$slug/roue',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces-suspendu': typeof AccesSuspenduRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roue': typeof RoueRoute
  '/super-admin': typeof SuperAdminRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug/': typeof MSlugIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces-suspendu': typeof AccesSuspenduRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roue': typeof RoueRoute
  '/super-admin': typeof SuperAdminRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug': typeof MSlugIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acces-suspendu': typeof AccesSuspenduRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roue': typeof RoueRoute
  '/super-admin': typeof SuperAdminRoute
  '/m/$slug/roue': typeof MSlugRoueRoute
  '/m/$slug/': typeof MSlugIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces-suspendu'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/reset-password'
    | '/roue'
    | '/super-admin'
    | '/m/$slug/roue'
    | '/m/$slug/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces-suspendu'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/reset-password'
    | '/roue'
    | '/super-admin'
    | '/m/$slug/roue'
    | '/m/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/acces-suspendu'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/confirmation'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/reset-password'
    | '/roue'
    | '/super-admin'
    | '/m/$slug/roue'
    | '/m/$slug/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesSuspenduRoute: typeof AccesSuspenduRoute
  AdminRoute: typeof AdminRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoueRoute: typeof RoueRoute
  SuperAdminRoute: typeof SuperAdminRoute
  MSlugRoueRoute: typeof MSlugRoueRoute
  MSlugIndexRoute: typeof MSlugIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces-suspendu': {
      id: '/acces-suspendu'
      path: '/acces-suspendu'
      fullPath: '/acces-suspendu'
      preLoaderRoute: typeof AccesSuspenduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roue': {
      id: '/roue'
      path: '/roue'
      fullPath: '/roue'
      preLoaderRoute: typeof RoueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug/': {
      id: '/m/$slug/'
      path: '/m/$slug'
      fullPath: '/m/$slug/'
      preLoaderRoute: typeof MSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug/roue': {
      id: '/m/$slug/roue'
      path: '/m/$slug/roue'
      fullPath: '/m/$slug/roue'
      preLoaderRoute: typeof MSlugRoueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesSuspenduRoute: AccesSuspenduRoute,
  AdminRoute: AdminRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmationRoute: ConfirmationRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoueRoute: RoueRoute,
  SuperAdminRoute: SuperAdminRoute,
  MSlugRoueRoute: MSlugRoueRoute,
  MSlugIndexRoute: MSlugIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
